name: McTranslit
main: me.galaran.mctranslit.McTranslit
version: 1.0
commands:
  translit:
      description: Set mode of chat transliteration
      usage: /translit [off in full dw]
  translittest:
      description: Prints transliterated message
      usage: /translittest <test message>
  detranslittest:
      description: Prints detransliterated message
      usage: /detranslittest <test message>
      
